### 사용자 조회
GET {{host}}/api/v1/users/1

### 회원가입
POST {{host}}/api/v1/users
Content-Type: application/json

{
  "accessToken": "9SBNUNXmS8WavoM07dVeozYrCufyKn0N8pQvotdxCisM0gAAAYasky4s",
  "nickname": "test22"
}

### 로그인
POST {{host}}/api/v1/users/login
Content-Type: application/json

{
  "accessToken": "9SBNUNXmS8WavoM07dVeozYrCufyKn0N8pQvotdxCisM0gAAAYasky4s"
}